/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205707;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ComputerTest {
    /**
     * コンピュータがファイルを読み込めるかの検証。
     * GameResultクラスからオブジェクトを生成、
     * テスト用の言葉を準備する（今回は「じゃば」）
     * 上の言葉をcomputerResultの引数として１回実行し、
     * 読み込んだ言葉が返されるか調べる
     */
    @Test
    void computerTest(){
        Computer computer = new Computer();
        Judge judge = new Judge();
        String testWprd = "じゃば"; 
        String one = computer.computerAnswer(testWprd ,judge);
        assertNotEquals(one, null);
    }

}
    