/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205707;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class GameResultTest {
    /**
     * コンピュータが同じ言葉を返さないことを検証。
     * GameResultクラスからオブジェクトを生成、
     * テスト用の言葉を準備する（今回は「じゃば」）
     * 上の言葉をcomputerResultの引数として2回実行し、
     * 違う言葉が返されるかを確かめる
     */
    @Test
    void computerResultTest(){
        GameResult game = new GameResult();
        String testWprd = "じゃば"; 
        assertNotEquals(game.computerResult(testWprd) , game.computerResult(testWprd));
    }

}
    