/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205707;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class JudgTest {
    /**
     * 文字がつながるかのテストで小文字と「ー」の扱いを検証。
     * 小文字は大文字の扱いで、「ー」は省かれている。
     * Judgクラスからオブジェクトを生成
     * つながる言葉を用意する。この時「ー」と小文字を入れる(今回は「しょー」と「よっと」)
     * wordConnectを実行し繋がっているのでtureになれば成功
     */
    @Test
    void wordConnectTest(){
        Judg judg = new Judg();
        String testBefor = "しょー";
        String testAfter = "よっと";
        assertEquals(judg.wordConnect(testBefor, testAfter) ,true);
    }
    
}
